
export const GET_SECTIONS = "GET_SECTIONS"
export const GET_SECTIONS_START = "GET_SECTIONS_START"
export const GET_SECTIONS_SUCCESS = "GET_SECTIONS_SUCCESS"
export const GET_SECTIONS_FAIL = "GET_SECTIONS_FAIL"
export const SET_SECTION_INFO = "SET_SECTION_INFO"


export const GET_LIST = "GET_LIST"
export const GET_LIST_START = "GET_LIST_START"
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS"
export const GET_LIST_FAIL = "GET_LIST_FAIL"
export const CLEAR_LIST = "CLEAR_LIST"

